program SIFOODT;

uses
  FMX.Forms,
  Winapi.Windows,
  uAdicionalView in 'shared\models\uAdicionalView.pas',
  uAdministradoraCartao in 'shared\models\uAdministradoraCartao.pas',
  uBandeiraCartao in 'shared\models\uBandeiraCartao.pas',
  uCaixa in 'shared\models\uCaixa.pas',
  uCaminhoImpressora in 'shared\models\uCaminhoImpressora.pas',
  uCidade in 'shared\models\uCidade.pas',
  uClass in 'shared\models\uClass.pas',
  uCliente in 'shared\models\uCliente.pas',
  uComprovante in 'shared\models\uComprovante.pas',
  uContaCliente in 'shared\models\uContaCliente.pas',
  uContaReceber in 'shared\models\uContaReceber.pas',
  uContaReceberCartao in 'shared\models\uContaReceberCartao.pas',
  uContato in 'shared\models\uContato.pas',
  uContaView in 'shared\models\uContaView.pas',
  uEmpresa in 'shared\models\uEmpresa.pas',
  uEndereco in 'shared\models\uEndereco.pas',
  uEstoque in 'shared\models\uEstoque.pas',
  uFormaPagamento in 'shared\models\uFormaPagamento.pas',
  uFormaPagamentoView in 'shared\models\uFormaPagamentoView.pas',
  uFuncoes in 'shared\models\uFuncoes.pas',
  uGrupoCofins in 'shared\models\uGrupoCofins.pas',
  uGrupoIcms in 'shared\models\uGrupoIcms.pas',
  uGrupoPis in 'shared\models\uGrupoPis.pas',
  uGrupoUsuario in 'shared\models\uGrupoUsuario.pas',
  uIBTP in 'shared\models\uIBTP.pas',
  uImpressora in 'shared\models\uImpressora.pas',
  uIndicador in 'shared\models\uIndicador.pas',
  uItemContaCliente in 'shared\models\uItemContaCliente.pas',
  uItemContaClienteView in 'shared\models\uItemContaClienteView.pas',
  uItemTransferenciaView in 'shared\models\uItemTransferenciaView.pas',
  uItemVenda in 'shared\models\uItemVenda.pas',
  uLancamentoCartaoView in 'shared\models\uLancamentoCartaoView.pas',
  uLocalEstoque in 'shared\models\uLocalEstoque.pas',
  uObservable in 'shared\models\uObservable.pas',
  uObservacao in 'shared\models\uObservacao.pas',
  uObservacaoView in 'shared\models\uObservacaoView.pas',
  uObserver in 'shared\models\uObserver.pas',
  uPagamentoPacialView in 'shared\models\uPagamentoPacialView.pas',
  uPagamentoParcial in 'shared\models\uPagamentoParcial.pas',
  uPagamentoPOSView in 'shared\models\uPagamentoPOSView.pas',
  uPos in 'shared\models\uPos.pas',
  uProduto in 'shared\models\uProduto.pas',
  uProdutoView in 'shared\models\uProdutoView.pas',
  uSat in 'shared\models\uSat.pas',
  uSecao in 'shared\models\uSecao.pas',
  uSecaoView in 'shared\models\uSecaoView.pas',
  uSetor in 'shared\models\uSetor.pas',
  uTipoVenda in 'shared\models\uTipoVenda.pas',
  uUnidadeMedida in 'shared\models\uUnidadeMedida.pas',
  uUsuario in 'shared\models\uUsuario.pas',
  uVenda in 'shared\models\uVenda.pas',
  uVendaFormaPagamento in 'shared\models\uVendaFormaPagamento.pas',
  uVendedor in 'shared\models\uVendedor.pas',
  uAdministradoraCartaoDAO in 'shared\dao\uAdministradoraCartaoDAO.pas',
  uBandeiraCartaoDAO in 'shared\dao\uBandeiraCartaoDAO.pas',
  uCaixaDAO in 'shared\dao\uCaixaDAO.pas',
  uClienteDAO in 'shared\dao\uClienteDAO.pas',
  uContaClienteDAO in 'shared\dao\uContaClienteDAO.pas',
  uContaReceberCartaoDAO in 'shared\dao\uContaReceberCartaoDAO.pas',
  uContaReceberDAO in 'shared\dao\uContaReceberDAO.pas',
  uEmpresaDAO in 'shared\dao\uEmpresaDAO.pas',
  uEstoqueDAO in 'shared\dao\uEstoqueDAO.pas',
  uFormaPagamentoDAO in 'shared\dao\uFormaPagamentoDAO.pas',
  uGrupoCofinsDAO in 'shared\dao\uGrupoCofinsDAO.pas',
  uGrupoIcmsDAO in 'shared\dao\uGrupoIcmsDAO.pas',
  uGrupoPisDAO in 'shared\dao\uGrupoPisDAO.pas',
  uGrupoUsuarioDAO in 'shared\dao\uGrupoUsuarioDAO.pas',
  uImpressoraDAO in 'shared\dao\uImpressoraDAO.pas',
  uIndicadorDAO in 'shared\dao\uIndicadorDAO.pas',
  uItemContaClienteDAO in 'shared\dao\uItemContaClienteDAO.pas',
  uItemVendaDAO in 'shared\dao\uItemVendaDAO.pas',
  uLocalEstoqueDAO in 'shared\dao\uLocalEstoqueDAO.pas',
  uObservacaoDAO in 'shared\dao\uObservacaoDAO.pas',
  uPagamentoParcialDAO in 'shared\dao\uPagamentoParcialDAO.pas',
  uPosDAO in 'shared\dao\uPosDAO.pas',
  uProdutoDAO in 'shared\dao\uProdutoDAO.pas',
  uSecaoDAO in 'shared\dao\uSecaoDAO.pas',
  uSetorDAO in 'shared\dao\uSetorDAO.pas',
  uTipoVendaDAO in 'shared\dao\uTipoVendaDAO.pas',
  uUnidadeMedidaDAO in 'shared\dao\uUnidadeMedidaDAO.pas',
  uUsuarioDAO in 'shared\dao\uUsuarioDAO.pas',
  UVendaDAO in 'shared\dao\UVendaDAO.pas',
  uVendedorDAO in 'shared\dao\uVendedorDAO.pas',
  uController in 'shared\interfaces\uController.pas',
  uConfiguracao in 'shared\models\uConfiguracao.pas',
  uConexaoFiredac in 'shared\models\uConexaoFiredac.pas',
  uDMConexao in 'shared\repository\uDMConexao.pas' {DMConexao: TDataModule},
  uFrmLogin in 'modules\login\uFrmLogin.pas' {FrmLogin},
  uFrmLoginController in 'modules\login\uFrmLoginController.pas',
  uFrmTecladoNumeric in 'modules\teclado_numeric\uFrmTecladoNumeric.pas' {FrmTecladoNumeric},
  uFrmTecladoNumericController in 'modules\teclado_numeric\uFrmTecladoNumericController.pas',
  uFrmTecladoAlphaNumeric in 'modules\teclado_alpha_numeric\uFrmTecladoAlphaNumeric.pas' {FrmTecladoAlphaNumeric},
  uFrmTecladoAlphaNumericController in 'modules\teclado_alpha_numeric\uFrmTecladoAlphaNumericController.pas',
  uFrmPrincipal in 'modules\principal\uFrmPrincipal.pas' {FrmPrincipal},
  uFrmPrincipalController in 'modules\principal\uFrmPrincipalController.pas',
  uFrmMesas in 'modules\mesas\uFrmMesas.pas' {FrmMesas: TFrame},
  uFrmMesasController in 'modules\mesas\uFrmMesasController.pas',
  uFrmComanda in 'modules\comanda\uFrmComanda.pas' {FrmComanda: TFrame},
  uFrmComandaController in 'modules\comanda\uFrmComandaController.pas',
  uFrmLiberaSenha in 'modules\libera_senha\uFrmLiberaSenha.pas' {FrmLiberaSenha},
  uFrmLiberaSenhaController in 'modules\libera_senha\uFrmLiberaSenhaController.pas',
  uFrmMensagem in 'modules\mensagem\uFrmMensagem.pas' {FrmMensagem},
  uFrmMensagemController in 'modules\mensagem\uFrmMensagemController.pas',
  uFrmLancamentoPOS in 'modules\lancamento_pos\uFrmLancamentoPOS.pas' {FrmLancamentoPOS},
  uFrmLancamentoPOSController in 'modules\lancamento_pos\uFrmLancamentoPOSController.pas',
  uFrmAlterarDadosvenda in 'modules\alterar_dados_venda\uFrmAlterarDadosvenda.pas' {FrmAlterarDadosVenda},
  uFrmAlterarDadosVendaController in 'modules\alterar_dados_venda\uFrmAlterarDadosVendaController.pas',
  uFrmLancamentoContasReceber in 'modules\lancamento_contas_receber\uFrmLancamentoContasReceber.pas' {FrmLancamentoContasReceber},
  uFrmLancamentoContasReceberController in 'modules\lancamento_contas_receber\uFrmLancamentoContasReceberController.pas',
  uFrmConsultaCliente in 'modules\consulta_cliente\uFrmConsultaCliente.pas' {FrmConsultaCliente},
  uFrmConsultaClienteController in 'modules\consulta_cliente\uFrmConsultaClienteController.pas';

{$R *.res}

begin
  Application.Initialize;

  Application.Title := 'Sistema de Restaurante Touch Screen - SI Informática';

  Application.CreateForm(TDMConexao, DMConexao);
  Application.CreateForm(TFrmLogin, FrmLogin);
  Application.Run;

end.
